### ISSUE TITLE
Image not loading

### ISSUE THREAD

**Issue by IronManCool001** [jmejiamu/the-tech-blog#5]
So I actually used your blog and added my profile picture but it was not loading...
![Screenshot from 2021-02-19 23-57-05](https://user-images.githubusercontent.com/63513685/108545737-30c6bf80-730e-11eb-8404-11bc372ce54c.png)

**Comment by jmejiamu** [comment]
First of all, thanks very much for using the blog, it really means a lot to me. Also, I had noticed the issue, but I have not had time to fix it yet. This is happening because the images don't have SSL so they are fetched as http://..., and netlify request https,  but  the pictures are actually there as you can see in the screenshot. I will fix that as soon as got time. Thanks for your time and your feedback. 
<img width="963" alt="issue" src="https://user-images.githubusercontent.com/27458911/108573729-3995a200-72ca-11eb-9fe3-e8e927c0ba35.png">

**Comment by IronManCool001** [comment]
Also there are lot of spams and useless messages you might want to remove them from the database as they occupy unnecessary space

**Comment by jmejiamu** [comment]
I am not really sure what do you mean by spams? I am not saving spams on the database

**Comment by jmejiamu** [comment]
What makes you thing I am saving spams in the database?

**Comment by IronManCool001** [comment]
![image](https://user-images.githubusercontent.com/63513685/108617580-a2e9f200-743d-11eb-88b6-4782ac94a2ee.png)
![image](https://user-images.githubusercontent.com/63513685/108617589-b1380e00-743d-11eb-95fc-f6f96ad10d33.png)
What are this aren't this empty posts and posts in language that literally very few people understand,so I consider this as spam

**Comment by jmejiamu** [comment]
I see  what you consider spams. Those are testes made from a community in Spanish from one guy who was interested in collaborate since it is an open source project now. But You are right I should delete those post. Thanks for letting me know.

**Comment by IronManCool001** [comment]
How do you send the posts data to the react app do you send a json response from the api ?

**Comment by jmejiamu** [comment]
Yes, I send it in a json format

**Comment by IronManCool001** [comment]
I see your API doesn't have the image.
![image](https://user-images.githubusercontent.com/63513685/108707336-db6cf700-7535-11eb-836a-19ddc217e382.png)

**Comment by jmejiamu** [comment]
BRO.  Fist of all, I already explain you what is going with the pictures. Second, the pictures are there save in the server. One more time it has to be with the http I need to add ssl certificate so they  have HTTPS. Lastly, YOU ARE LOOKING AT THE WRONG URL FOR THE IMAGES.   if you want to test that you can allow under setting insecure content and you will be able to see the pictures, so one last time it has to be with the https the images has http. Here is an example. I allow insecure content and I am able to see the pictures
![imageissue](https://user-images.githubusercontent.com/27458911/108773352-101b8700-7513-11eb-8bad-d036b0ba9db2.jpg)

**Comment by IronManCool001** [comment]
I have allowed insecure content for your website and now the images does
load

**Comment by jmejiamu** [comment]
Bro, I am not sure what you are doing wrong, I just did it in Brave (allow Insecure content) refresh the page and it shows the pictures. Please let me know what you dont understand I can help you.
