### ISSUE TITLE
Login is temporary

### ISSUE THREAD

**Issue by IronManCool001** [jmejiamu/the-tech-blog#6]
When I login the next time I try to access I get logged out

**Comment by jmejiamu** [comment]
I don't  really understand here what you mean. There is a time set of 45 minutes after that you will be logged out.

**Comment by IronManCool001** [comment]
Why it is so make it for at least 1 month cause it is irritating to use my
email and password after every 45 minutes

**Comment by jmejiamu** [comment]
I think I already explain why I did it like that in my previous response.

**Comment by IronManCool001** [comment]
Okay I actually didn't see the full response cause I was seeing it from gmail

**Comment by IronManCool001** [comment]
But I would appreciate if it could be increased to 60 minutes

**Comment by jmejiamu** [comment]
I will do that as soon as I get time and thanks for your comments. All of the observation help us to improve.
